### PR TITLE
updated gnome versions metadata to include 3.20

### PR DESCRIPTION
**Pull request by james-nesbitt**
This patch is an early 3.20 support patch.  It does nothing more than update the metadata (and readme) to indicate that 3.20 is supported.

Test it before merging.

### CODE REVIEW

**Comment by olystretch** [comment]
This change works for me, using Gnome 3.20.0 on Arch

**Comment by jdtournier** [comment]
Seems to work fine for me too, Gnome 3.20.1, also on Arch.

**Comment by Tirip** [comment]
Not sure if spin83 is still active. Maybe it's time to fork and make code available to extensions.gnome.org? It's only really the metadata that needs to be updated.

**Comment by smcdougall** [comment]
@Trip His last activity was March 7th.  This is a great extension, and I'd hate to see it die off.  If he's not interested in maintaining it, maybe someone else could step up.  Most of the updates have been to the metadata anyway, so it really just needs someone with the time to accept occasional pull requests.

**Comment by Tirip** [comment]
@smcdougall Didn't see that March activity - thought he was inactive since last October. Anyhow, I'm absolutely with you, this extension is a must have for multimonitors and it needs to stay alive. But I guess we're going off-topic.

**Comment by smcdougall** [comment]
Indeed.  In that case, I'll add that although I haven't tried this pull request exactly, I have manually added `3.20` to my locally-installed copy and haven't noticed any issues under Arch with Gnome 3.20.x. :smiley:

**Pull request merged**
